type ResponseMap = {
    id?: number; // Optional because the ID might be generated by the database
    user_id: string;
    question_id: number;
    total_attempts?: number;
    correct_attempts?: number;
  };
  
  class Response {
    id?: number;
    userId: string;
    questionId: number;
    totalAttempts: number;
    correctAttempts: number;
  
    constructor({
      id,
      userId,
      questionId,
      totalAttempts = 0,
      correctAttempts = 0,
    }: {
      id?: number;
      userId: string;
      questionId: number;
      totalAttempts?: number;
      correctAttempts?: number;
    }) {
      this.id = id;
      this.userId = userId;
      this.questionId = questionId;
      this.totalAttempts = totalAttempts;
      this.correctAttempts = correctAttempts;
    }
  
    // Factory method to create a Response instance from Supabase row (map)
    static fromMap(map: ResponseMap): Response {
      return new Response({
        id: map.id,
        userId: map.user_id,
        questionId: map.question_id,
        totalAttempts: map.total_attempts ?? 0,
        correctAttempts: map.correct_attempts ?? 0,
      });
    }
  
    // Convert a Response object to a Map (for inserting into Supabase)
    toMap(): ResponseMap {
      return {
        user_id: this.userId,
        question_id: this.questionId,
        total_attempts: this.totalAttempts,
        correct_attempts: this.correctAttempts,
      };
    }
  }
  
  export default Response;
  